import { MD3DarkTheme, MD3LightTheme, MD3Theme } from 'react-native-paper'


const brandLight = {
  primary: '#F97316',
  surfaceTint: '#F97316',
  onPrimary: '#FFFFFF',
  primaryContainer: '#FFEDD5',
  onPrimaryContainer: '#7C2D12',
  secondary: '#64748B',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#F1F5F9',
  onSecondaryContainer: '#334155',
  tertiary: '#10B981',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#D1FAE5',
  onTertiaryContainer: '#065F46',
  error: '#E53935',
  onError: '#FFFFFF',
  errorContainer: '#FFEBEE',
  onErrorContainer: '#7F1D1D',
  background: '#FFFFFF',
  onBackground: '#1A1A1A',
  surface: '#FFFFFF',
  onSurface: '#1A1A1A',
  surfaceVariant: '#F8F8F8',
  onSurfaceVariant: '#5F6368',
  outline: '#DADCE0',
  outlineVariant: '#F1F3F4',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#1F2937',
  inverseOnSurface: '#F9FAFB',
  inversePrimary: '#FDBA74',
  primaryFixed: '#FFEDD5',
  onPrimaryFixed: '#7C2D12',
  primaryFixedDim: '#FB923C',
  onPrimaryFixedVariant: '#EA580C',
  secondaryFixed: '#F1F5F9',
  onSecondaryFixed: '#334155',
  secondaryFixedDim: '#94A3B8',
  onSecondaryFixedVariant: '#475569',
  tertiaryFixed: '#D1FAE5',
  onTertiaryFixed: '#065F46',
  tertiaryFixedDim: '#6EE7B7',
  onTertiaryFixedVariant: '#047857',
  surfaceDim: '#E8EAED',
  surfaceBright: '#FFFFFF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FAFBFC',
  surfaceContainer: '#F5F6F7',
  surfaceContainerHigh: '#F0F1F2',
  surfaceContainerHighest: '#E8EAED',
};

/**
 * 暗色主题
 */
const brandDark = {
  primary: '#FB923C',
  surfaceTint: '#FB923C',
  onPrimary: '#7C2D12',
  primaryContainer: '#C2410C',
  onPrimaryContainer: '#FFEDD5',
  secondary: '#94A3B8',
  onSecondary: '#334155',
  secondaryContainer: '#475569',
  onSecondaryContainer: '#F1F5F9',
  tertiary: '#6EE7B7',
  onTertiary: '#065F46',
  tertiaryContainer: '#047857',
  onTertiaryContainer: '#D1FAE5',
  error: '#EF9A9A',
  onError: '#7F1D1D',
  errorContainer: '#C62828',
  onErrorContainer: '#FFEBEE',
  background: '#121212',
  onBackground: '#F5F5F5',
  surface: '#121212',
  onSurface: '#F5F5F5',
  surfaceVariant: '#2D2D2D',
  onSurfaceVariant: '#D1D5DB',
  outline: '#6B7280',
  outlineVariant: '#4B5563',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#F5F5F5',
  inverseOnSurface: '#1F2937',
  inversePrimary: '#F97316',
  primaryFixed: '#FFEDD5',
  onPrimaryFixed: '#7C2D12',
  primaryFixedDim: '#FB923C',
  onPrimaryFixedVariant: '#EA580C',
  secondaryFixed: '#F1F5F9',
  onSecondaryFixed: '#334155',
  secondaryFixedDim: '#94A3B8',
  onSecondaryFixedVariant: '#475569',
  tertiaryFixed: '#D1FAE5',
  onTertiaryFixed: '#065F46',
  tertiaryFixedDim: '#6EE7B7',
  onTertiaryFixedVariant: '#047857',
  surfaceDim: '#0F0F0F',
  surfaceBright: '#1E1E1E',
  surfaceContainerLowest: '#0A0A0A',
  surfaceContainerLow: '#1A1A1A',
  surfaceContainer: '#1E1E1E',
  surfaceContainerHigh: '#282828',
  surfaceContainerHighest: '#353535',
};

function buildTheme(mode: 'light' | 'dark'): MD3Theme {
  const base = mode === 'dark' ? MD3DarkTheme : MD3LightTheme
  const palette = mode === 'dark' ? brandDark : brandLight

  return {
    ...base,
    roundness: 4, 
    colors: {
      ...base.colors,
      ...palette,
    },
  }
}

export function getMD3Theme(mode: 'light' | 'dark'): MD3Theme {
  return buildTheme(mode)
}
