import { MD3DarkTheme, MD3LightTheme, MD3Theme } from 'react-native-paper'

const brandLight = {
  primary: '#7A590C',
  surfaceTint: '#7A590C',
  onPrimary: '#FFFFFF',
  primaryContainer: '#FFDEA5',
  onPrimaryContainer: '#271900',
  secondary: '#6C5C3F',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#F6E0BB',
  onSecondaryContainer: '#251A04',
  tertiary: '#4C6545',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#CEEBC2',
  onTertiaryContainer: '#0A2007',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#410002',
  background: '#FFFBF7',
  onBackground: '#201B13',
  surface: '#FFFBF7',
  onSurface: '#201B13',
  surfaceVariant: '#EEE1CF',
  onSurfaceVariant: '#4E4639',
  outline: '#7F7667',
  outlineVariant: '#D1C5B4',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#353027',
  inverseOnSurface: '#FAEFE2',
  inversePrimary: '#ECC06C',
  primaryFixed: '#FFDEA5',
  onPrimaryFixed: '#271900',
  primaryFixedDim: '#ECC06C',
  onPrimaryFixedVariant: '#5D4200',
  secondaryFixed: '#F6E0BB',
  onSecondaryFixed: '#251A04',
  secondaryFixedDim: '#D9C4A0',
  onSecondaryFixedVariant: '#53452A',
  tertiaryFixed: '#CEEBC2',
  onTertiaryFixed: '#0A2007',
  tertiaryFixedDim: '#B2CFA7',
  onTertiaryFixedVariant: '#354D2F',
  surfaceDim: '#E3D8CC',
  surfaceBright: '#FFFBF7',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#FDF2E5',
  surfaceContainer: '#F7ECDF',
  surfaceContainerHigh: '#F1E7D9',
  surfaceContainerHighest: '#ECE1D4',
};

const brandDark = {
  primary: '#ECC06C',
  surfaceTint: '#ECC06C',
  onPrimary: '#412D00',
  primaryContainer: '#5D4200',
  onPrimaryContainer: '#FFDEA5',
  secondary: '#D9C4A0',
  onSecondary: '#3C2E15',
  secondaryContainer: '#53452A',
  onSecondaryContainer: '#F6E0BB',
  tertiary: '#B2CFA7',
  onTertiary: '#1F361A',
  tertiaryContainer: '#354D2F',
  onTertiaryContainer: '#CEEBC2',
  error: '#FFB4AB',
  onError: '#690005',
  errorContainer: '#93000A',
  onErrorContainer: '#FFDAD6',
  background: '#17130B',
  onBackground: '#ECE1D4',
  surface: '#17130B',
  onSurface: '#ECE1D4',
  surfaceVariant: '#4E4639',
  onSurfaceVariant: '#D1C5B4',
  outline: '#9A8F80',
  outlineVariant: '#4E4639',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#ECE1D4',
  inverseOnSurface: '#353027',
  inversePrimary: '#7A590C',
  primaryFixed: '#FFDEA5',
  onPrimaryFixed: '#271900',
  primaryFixedDim: '#ECC06C',
  onPrimaryFixedVariant: '#5D4200',
  secondaryFixed: '#F6E0BB',
  onSecondaryFixed: '#251A04',
  secondaryFixedDim: '#D9C4A0',
  onSecondaryFixedVariant: '#53452A',
  tertiaryFixed: '#CEEBC2',
  onTertiaryFixed: '#0A2007',
  tertiaryFixedDim: '#B2CFA7',
  onTertiaryFixedVariant: '#354D2F',
  surfaceDim: '#17130B',
  surfaceBright: '#3E382F',
  surfaceContainerLowest: '#120E07',
  surfaceContainerLow: '#201B13',
  surfaceContainer: '#241F17',
  surfaceContainerHigh: '#2F2921',
  surfaceContainerHighest: '#3A342B',
};

function buildTheme(mode: 'light' | 'dark'): MD3Theme {
  const base = mode === 'dark' ? MD3DarkTheme : MD3LightTheme
  const palette = mode === 'dark' ? brandDark : brandLight

  return {
    ...base,
    roundness: 5,
    colors: {
      ...base.colors,
      ...palette,
    },
  }
}

export function getMD3Theme(mode: 'light' | 'dark'): MD3Theme {
  return buildTheme(mode)
}
